chore: Add the startWithTimeout method to ensure a timeout is used
launchdarkly/flutter-client-sdk pull request #159
Opened 2024-05-09 09:51 UTC by louis-launchdarkly

Because the current start method returns a future, to not create behavioral change, it probably makes sense to create a new method to use.

2024-05-09 14:19 UTC, tanderson-ld requested changes

2024-05-09 14:19 UTC, tanderson-ld commented on packages/common_client/lib/src/ld_common_client.dart
> +  /// then the SDK has encountered an unrecoverable error. If
I don't believe it is true that the timeout firing means it has encountered an unrecoverable error.  I think the SDK will continue to attempt to get flag data.

Some SDKs use "waitTime" as the parameter.  I like that that name more (my opinion) than timeout for SDKs that do continue to try to get flag data.  Something to consider.

2024-05-09 14:19 UTC, tanderson-ld commented on packages/common_client/lib/src/ld_common_client.dart
> +    if (timeout > Duration(seconds: 15)) {
15 should be a const.

2024-05-09 14:19 UTC, tanderson-ld commented on packages/flutter_client_sdk/lib/src/ld_client.dart
> +  Future<bool> startWithTimeout(Duration timeout) async {
Documentation is needed

2024-05-20 14:58 UTC, kinyoklion requested changes
I am confused here. I thought we were an optional timeout to the one method, it warns you when you don't use it. Next major version we make the timeout either mandatory or default to a value when not specified.

Requesting changes as to not lose track.

2024-12-13 18:24 UTC, closed without merging